### ISSUE TITLE
Cydia 下载软件包提示 HTTP/1.1 404 NOT Found

### ISSUE THREAD

**Issue by haoerloveyou** [82Flex/WEIPDCRM#13]
在源后台上传好的包，并刷新packages后 cydia 下载 deb 提示 HTTP/1.1 404 NOT Found

特来请教一下。

**Comment by haoerloveyou** [comment]
我发现同一个软件包 点开管理软件包里显示的 filename 和 packeages 里面的filename 不同。
 如点开软件管理里Filename  ../downloads/20150701/YjocHzJGpCKH6xXr3jCXsOQD7FzVsOcRV63RmWvR.deb
 刷新 packages看到的   Filename: ./debs/2.deb

**Comment by Hintay** [comment]
请检查Rewrite模块是否正常

**Comment by haoerloveyou** [comment]
ls能否详细一点 感谢，我的测试地址是cydia.space

**Comment by haoerloveyou** [comment]
感谢ls 确实是 rewrite问题。最开始没阅读说明。用的iis 而且还没有开启rewrite。白折腾1天。换了apache，打开rewrite问题解决 感谢提醒！
