### ISSUE TITLE
GPG error

### ISSUE THREAD

**Issue by iphonefacil** [82Flex/WEIPDCRM#14]
I get this error:
GPG error: [my repo url] ./ Release: The following signatires were invalid: NODATA 1 NODATA 2

Please, I need help.

Great job!!

**Comment by Lessica** [comment]
Disable the GPG Signature Function and check the gpg installed on your server. You should have the privilege of running the gpg and configure it correctly before using this security function.

**Comment by iphonefacil** [comment]
Thaks a lot for your answer but, how can I disable the GPG Signature Function ?

**Comment by Hintay** [comment]
Please set `define("DCRM_GNUPG_ENABLED", 0);` in `./system/config/gnupg.inc.php` to disable the GPG signature function.

**Comment by iphonefacil** [comment]
No way, the problem continues

**Comment by Hintay** [comment]
Please Rebuld the list, then check the Release file in your repo directory.

**Comment by iphonefacil** [comment]
Still not working but I have realized that it is related t .htaccess

**Comment by iphonefacil** [comment]
I have tried everything and in different hostings and I get the same problem 
My source http://iphonefacil.tk/cydia 
Any idea, please?
![image](https://cloud.githubusercontent.com/assets/4551593/8719987/fdf09a5a-2baf-11e5-9c56-20115ab3d4ac.jpg)

**Comment by Lessica** [comment]
I have tested your server and it jumped to http://www.hostinger.com.hk/error_404 when I tried to visit a unreachable page. Cydia will try to get "Release.gpg" when you refresh Packages List in Cydia, but it do not return a "404 not found" status code but a "301 Moved Permanently" actually. It confused Cydia and caused this problem. Your website must return a standard "404 Code" when an object can't be found. So, ask Hostinger for help.

**Comment by Lessica** [comment]
You'd better build WEIPDCRM on an VPS.

**Comment by iphonefacil** [comment]
Now all works fine in http://repo.iphonefacil.tk/ except for thin error -> "GPG error: http://repo.iphonefacil.tk ./ Release: The following signatures were invalid: NODATA 1 NODATA 2"

**Comment by Lessica** [comment]
http://repo.iphonefacil.tk/Release.gpg should return a 404 error, not a specific "not found" page. Contact your webmaster, please.

**Comment by iphonefacil** [comment]
Thanks!!!!! 
I have solved it by pasting this in your .htaccess 
"ErrorDocument 404 "<H1>Page not found</H1>""

Issue can de closed.

Another thing, I would like to help to translate WEIPCRM into Spanish...

**Comment by Lessica** [comment]
You're welcome.
WEIPDCRM uses .po and .mo to be localized.
You can fork a new branch, and make a pull request.
Thanks :-)
