### ISSUE TITLE
Hash Sum mismatch

### ISSUE THREAD

**Issue by haoerloveyou** [82Flex/WEIPDCRM#15]
把别人源的ifile 下载后上传到自己源，即使重新打包，cydia一直提示 Hash Sum mismatch
来咨询下。感谢

**Comment by haoerloveyou** [comment]
不仅是ifile 很多插件都出现 Hash sum mismatch  cydia 检校 哈希一直过不了

**Comment by pb8DvwQkfRR** [comment]
有改package名称么? Cydia完整刷新过了么? Rebuild按钮点过没?

**Comment by Hintay** [comment]
若以上方法均无效，请尝试在设置中修改检验方式后再次刷新列表。

**Comment by haoerloveyou** [comment]
回复zsm1703 以上方法均无效，就算我原生不动，上传别人的ifile包（以ifile举例） 依然报错（在别人源又能正常下载）。且不说我改过没改过了。

**Comment by haoerloveyou** [comment]
回hinatay 感谢 马上试试

**Comment by Lessica** [comment]
你上传软件包必须修改软件包标识符，，并且必须立即写入软件包，显示软件包，然后刷新列表。

**Comment by haoerloveyou** [comment]
回 82 在源设置默认情况下，我修不修标识符改都报错，马上 用hintay的方法试试。

**Comment by ljk4160** [comment]
上传修改插件后，要刷新源，这时校验码变更。手机下载的时候进入cydia也要刷新，否者旧的校验码与刷新后的校验码对不上就会出错

**Comment by haoerloveyou** [comment]
回各位  很遗憾，用Hintay 的方法 问题依然存在，即使我把验证方式改为不验证（每种验证方式都测试了）并且 改动了列表压缩方式（每种列表方式都测试了）问题依然存在。测试源地址cydia.space 测试ifile包来之weip repo

**Comment by haoerloveyou** [comment]
回JK 我肯定刷新了哦。repo端 我刷新了列表 手机端 我刷新了源。

**Comment by Lessica** [comment]
首先确保服务器文件系统权限正常，然后请按照我说的步骤操作一遍，不要跳步骤。
1、上传来自其它源的软件包。
2、导入该软件包。
3、选中，并进入常规编辑。
4、修改软件包标识符。
5、保存，并点击立即写入。（修改了带星号的字段都必须立即写入）
6、选中，并刷新列表。
7、打开 Cydia，刷新源列表。
8、尝试安装。

**Comment by haoerloveyou** [comment]
另外反馈个情况，并不是每个包都出现这样的问题，我自己写的小插件不会出现这个错误。个别其他源的插件也不会出现这个错误。但有些软件问题存在。比如测试源内的ifile，kuaidial等。继续按82的方法再去测试一遍

**Comment by haoerloveyou** [comment]
反馈下，除了ifile 我源内所有软件全部正常，我想起个事情，ifile 上传的时候过大了（7M）。我是用ftp上传的。难道 有这个原因？

**Comment by ljk4160** [comment]
检查下上传有否损坏

**Comment by haoerloveyou** [comment]
回JK 马上去核实

**Comment by haoerloveyou** [comment]
问题初步找到，服务器端文件没有问题，在cydia下载缓存内"/user/library/cache/.../patal/" cydia 文件根本没下完 手机端就开始安装了。下载ifile的大小不等，有的几百kb 有的1-2m,共同的特点就是都没下载完。这样hash检校 肯定不过了。问题是找到了。但不知道解决方法，还请各位不吝相助。感谢

**Comment by haoerloveyou** [comment]
服务器 大致情况是 win2003 apach+php+mysql 5M独享

**Comment by Lessica** [comment]
可能是由于文件过大，php 传输执行超时导致中途断开？可以检查一下 php 超时时间。

**Comment by haoerloveyou** [comment]
回82 ：我检查了php.ini默认超时时间是 30秒，下载过程肯定没到30秒，是不是你程序设置的传输超时短了？请问你设置传输超时的具体是哪个文件，可否告知一下，我好检测调整。

**Comment by Lessica** [comment]
并没有设置超时时间，请检查 downloads.php，并关闭防盗链，用 http://xxx.com/debs/1.deb 在PC端下载检查文件完整性。

**Comment by haoerloveyou** [comment]
回82 通过你提供的方法，发现从web下载依然出现文件中断现象，而且基本与cydia下载 中断保持一直 2M左右就中断了，已经联系idc 他也在找问题。

**Comment by haoerloveyou** [comment]
回82 通过你的方法，发现在电脑web端下载也出现下载中断的现象，并且与cydia下载中断保持一致，2m左右就自动断开下载。已联系idc 找问题。

**Comment by haoerloveyou** [comment]
回来者：问题已解决。原因：机房垃圾网速慢导致php默认30秒超时自动断开。解决办法：修改php.ini max_execution_time = 60  （单位秒） 感谢各位，撒花。 
To everyone :+1:  this problem has already been resolved. Reason: the rubbish IDC Network speed causes php default 30 seconds timeout then Server automatically disconnected. Solution: Modify php.ini max_execution_time = 60 (seconds) Thank you

**Comment by Lessica** [comment]
是的，因为目前采用 php 处理软件包数据传输和重定向，所以会受到 php 配置影响，性能上也不如 http 服务端传输静态文件来得好，后续将会改善软件包存储机制和鉴定方式。

**Comment by haoerloveyou** [comment]
是的，IDC客服，最后愤愤的丢下一句，下载用什么php啊。。。
