### ISSUE TITLE
显示软件包无反应

### ISSUE THREAD

**Issue by ZhangShanFeng1114** [82Flex/WEIPDCRM#16]
点击“显示软件包”，没有任何反应。

**Comment by Lessica** [comment]
浏览器问题，使用 Chrome 即可，因为精力有限，暂不打算兼容其它浏览器，请使用 Webkit 内核的浏览器。

**Comment by Hintay** [comment]
现只兼容IE10+、Webkit内核浏览器（如Chrome、Safari等）及Firefox等现代浏览器。

**Comment by ZhangShanFeng1114** [comment]
好的，收到。
