### ISSUE TITLE
中文语言文件修改不生效

### ISSUE THREAD

**Issue by ZhangShanFeng1114** [82Flex/WEIPDCRM#18]
system\languages\zh_CN.po 文件已更改汉化文字，更改不生效。

**Comment by Hintay** [comment]
修改 PO 文件后需要编译 MO 文件，gettext 国际化系统并非直接读取 PO 文件内字符串。

创建 Issues 前请先尝试自行解决，自行无法解决的再向开发者寻求帮助。

**Comment by ZhangShanFeng1114** [comment]
好的 感谢
