### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by 0xJacky** [82Flex/WEIPDCRM#21]
![qq20150715-1](https://cloud.githubusercontent.com/assets/13096985/8701618/809a6be0-2b45-11e5-9a67-2e91c8b58af0.png)

![qq20150715-2](https://cloud.githubusercontent.com/assets/13096985/8701640/9898419a-2b45-11e5-84ed-2848594adef9.png)

好像哪里不对

 ![qq20150715-3](https://cloud.githubusercontent.com/assets/13096985/8702057/eb3b4774-2b47-11e5-9f04-605ff61f6522.png)
在设置页面 设置好了内容 保存后就提示无法访问的问题，但实际上已经应用了

**Comment by Jackyxyz** [comment]
![qq20150715-3](https://cloud.githubusercontent.com/assets/13096985/8702057/eb3b4774-2b47-11e5-9f04-605ff61f6522.png)
在设置页面 设置好了内容 保存后就提示无法访问的问题，但实际上已经应用了
