### ISSUE TITLE
Rewrite配置已经更新了 但还是无法启用Rewrite模式 

### ISSUE THREAD

**Issue by 0xJacky** [82Flex/WEIPDCRM#22]
1.7Pro开始，普通模式和优雅模式都无法启用。iis里面已经重新转换过1.7版dcrm_apache.htaccess了。
设置后提示：
![qq20150717-1](https://cloud.githubusercontent.com/assets/13096985/8740012/b652cab2-2c75-11e5-8303-11130a832459.png)
还有非常奇葩的是可以直接访问伪静态处理后的页面，都是可以正常访问的
![qq20150717-2](https://cloud.githubusercontent.com/assets/13096985/8740046/58997960-2c76-11e5-8c45-a2a7eed8168a.png)
![qq20150717-3](https://cloud.githubusercontent.com/assets/13096985/8740048/58ea1ae6-2c76-11e5-9f35-80d346a460c7.png)
![qq20150717-4](https://cloud.githubusercontent.com/assets/13096985/8740047/58e42a5a-2c76-11e5-93b4-481623221e19.png)

**Comment by Hintay** [comment]
请更新至 Commit 78ce734 并及时反馈。

**Comment by 0xJacky** [comment]
ok可以启用优雅模式了
