### ISSUE TITLE
多说评论框的配置方法 (How to configure duoshuo, for Chinese users only.)

### ISSUE THREAD

**Issue by 0xJacky** [82Flex/WEIPDCRM#23]
![33d4e17c-2cd6-11e5-8f1b-56675aed287c](https://cloud.githubusercontent.com/assets/13096985/9025400/c5eff702-3935-11e5-8f83-63beb4bdb67d.png)

DCRM设置里面有一栏填写【多说社会化评论框key】实际上需要填写的并不是KEY 而是用户在创建站点时填写的“多说域名”（如下图）

![8ba15458-2cd6-11e5-8442-c46d5dd9bd64](https://cloud.githubusercontent.com/assets/13096985/9025401/cc1aae06-3935-11e5-9018-6890b3a6d9e0.png)

所以正确的填写方式应该为：

![47e66d7e-2cd7-11e5-88b6-d1082b243ca5](https://cloud.githubusercontent.com/assets/13096985/9025402/d5bbdc46-3935-11e5-86c7-4beb7ac88c78.png)

但是新的问题来了，评论框在4英寸设备中（iPhone 5 5s 5c iPod touch 5&6 ）评论框超出了页面的宽度

**Comment by Lessica** [comment]
请在多说后台添加 CSS：
    #ds-thread{margin-bottom:20px;}
    #ds-thread #ds-reset .ds-powered-by{display:none;}
    #ds-thread #ds-reset li.ds-tab a.ds-current{background:none;border:none;}
    .ds-sync{display:none !important;}
    #ds-reset > div.ds-login-buttons > div{width: auto !important;}

**Comment by 0xJacky** [comment]
感谢 ^_^

**Comment by Hintay** [comment]
Issues 解决后标题请尽量保持原样以供后人参考，由开发者关闭即表示为已解决。

**Comment by 0xJacky** [comment]
抱歉，还好有备份文章
