### ISSUE TITLE
建议能批量上传截图

### ISSUE THREAD

**Issue by 0xJacky** [82Flex/WEIPDCRM#24]
如题

**Comment by Hintay** [comment]
该特性已在 Commit 8213720 中增加。新功能可能不太稳定，若有 bug 请及时反馈。

**Comment by 0xJacky** [comment]
我来总结下bug吧
1.批量上传后，图片检测不到
![qq20150802-10](https://cloud.githubusercontent.com/assets/13096985/9025901/3fc618c6-394b-11e5-88af-09c5935e8078.png)
2.保存后，图片的路径出现错误
![qq20150802-11](https://cloud.githubusercontent.com/assets/13096985/9025902/4dd4c926-394b-11e5-8c40-98f06183166c.png)
3.更换上传方式（使用单个上传）
![qq20150802-12](https://cloud.githubusercontent.com/assets/13096985/9025906/60440b76-394b-11e5-98c1-e7b85a8095dc.png)
路径也是出问题了
4.最后在【文件空间】发现，图片保存的路径错误了，以前是保存在./manage/image下的。现在改到了./image下
![qq20150802-13](https://cloud.githubusercontent.com/assets/13096985/9025907/7f3adcf8-394b-11e5-894b-bd4cd02f2735.png)

**Comment by Hintay** [comment]
路径本来就应该是 /image 而非 /manage/image，是之前整合框架时遗留下的错误。此次修正了这个错误，并在子目录下测试成功。
路径还需进一步修正。

**Comment by 0xJacky** [comment]
嗯，路径正常后，这个功能就完美了。

**Comment by Hintay** [comment]
你使用的是 IIS 环境？

**Comment by 0xJacky** [comment]
嗯

**Comment by Hintay** [comment]
有 IIS 的静态配置吗？我本地测试下

**Comment by 0xJacky** [comment]
稍等

**Comment by 0xJacky** [comment]
apt.jackyu.cn/web.config.zip

**Comment by Hintay** [comment]
已在 Commit 1d69c5e 中修复，请更新并及时反馈。
