### ISSUE TITLE
问题反馈，功能改进

### ISSUE THREAD

**Issue by zikexiaozi** [82Flex/WEIPDCRM#25]
1、保护功能取消后，保护依然显示，查换原因，保护标签依然存在。
2、后台描述编辑器，经常串位，不对齐。
3、软件截图上传大小有限制，在哪里修改。建议说明修改位置
4、后台生成软件图标有问题，安装后依然不显示

**Comment by Hintay** [comment]
1.请提供数据库中无法关闭保护的软件包的Tag字段。最好是提供整份数据库备份。
2.哪个描述？详细描述还是描述？
3.这是php限制，请修改php配置文件。
4.软件图标？是否指分类图标？若是分类图标，请先检查分类名中有无斜杠等会是程序错乱的字符，若还无效请提供分类名与图标。

**Comment by zikexiaozi** [comment]
1、比如在BIGBOSS源下载的收费插件barrel，上传导入后，显示的是保护开启，当手动改为保护禁用，但在高级编辑里面的tag依然有cydia::commercial,并没有被删除。如果上传的插件本来就是没有被保护的，启动和禁用均无BUG
2、详细描述与更新日志的编辑器，填写内容，保存后，在手机打开网页经常出现与编辑器显示不一致，出现错行。排序出错，但无乱码。
3、软件截图上传大小有限制，服务器设置为20M，图片并没有20M,应该是由程序控制的上传大小限制。
4、分类图标生成的图标包，在已安装文件里面查看，路径并不是
APPlications
   Cydia.app
      Sections
   而是 APPlications/Cydia.app/Sections  在一排。导致图标包无效。本人无任何修改，在手机段将图标包，直接解包，再打包。上传，导入，使用正常。

**Comment by zsm1703** [comment]
1.的保护并不是tag中的需要付费的保护. 而是UDID保护

**Comment by Jackyxyz** [comment]
解包编辑掉tap不就完了嘛

**Comment by Hintay** [comment]
请以开发人员回复为准。
第一项已确定为bug，已有修复方案，还需测试。
第二项请提供有问题的详细描述或更新日志原文，即数据库中保存的数据。
第三、四项正在排查中。

**Comment by Jackyxyz** [comment]
嗯 但目前的紧急解决方案是这样的

发自我的 iPhone

**Comment by Hintay** [comment]
1、3已在 Commit 5a5d1b4 中修复。
第二项：请提供有问题的详细描述或更新日志原文，即数据库中保存的数据。
第四项：经过实际测试， APPlications/Cydia.app/Sections 为一行是正常的，且图标文件已被安装到正确位置。但在测试中发现一个无法安装（Control 文件末尾无新行）以及另一个会使 Cydia 闪退（默认无分类）的 BUG，这两个 BUG 均已在 Commit 5a5d1b4 中修复。

**Comment by Lessica** [comment]
获取商业支持请联系授权邮箱 i.82@me.com，这里不欢迎伸手党。顺便说句，反馈问题并期待修复请带敬辞，虽然是 @Hintay 解决，但是我也看不下去了。
