### ISSUE TITLE
分类列表中“更多”按钮无法使用的问题反馈

### ISSUE THREAD

**Issue by T0nny** [82Flex/WEIPDCRM#26]
1.浏览器Safari
![qq20150802-1](https://cloud.githubusercontent.com/assets/13607950/9025086/a64632f4-3926-11e5-955a-60a39e78a2bc.png)
2.填写了cnzz的统计，但是cnzzn那边没有统计出来额。服务器在香港 系统win2008r2，不知道是什么问题。

**Comment by Hintay** [comment]
请提供源地址。

**Comment by Hintay** [comment]
“更多...”按钮已在 Commit 91481b7 中修复。
统计功能请提供源地址，需要更多信息来测试。

**Comment by 0xJacky** [comment]
刚才登错账号，难怪收不到邮件提示。。
源地址是：apt.jackyu.cn
因为cnzz统计不了
所以暂时用百度统计来统计，百度统计有个统计代码自动安装的功能，但每次更新后都要执行一遍，十分不方便。。

**Comment by Jackyxyz** [comment]
额 Commit 91481b7 并没有解决“更多..”按钮的问题

**Comment by Hintay** [comment]
从页面源码来看，输出的统计代码中有错误的转义符号。请贴上设置中统计代码的截图以供参考。

**Comment by 0xJacky** [comment]
![qq20150802-5](https://cloud.githubusercontent.com/assets/13096985/9025798/d159c250-3947-11e5-98ae-4e0c207afbb3.png)

**Comment by Hintay** [comment]
请贴出 ./system/config/autofill.inc.php 中 AUTOFILL_STATISTICS 的内容。

**Comment by 0xJacky** [comment]
![qq20150802-14](https://cloud.githubusercontent.com/assets/13096985/9026674/e3bcbd04-3969-11e5-8799-4127a3986a23.png)

**Comment by Hintay** [comment]
出现了超多的转义字符‘\’，请先在设置中清空保存后再重新填入后再贴出 AUTOFILL_STATISTICS。

**Comment by 0xJacky** [comment]
您好大神，重新保存了仍然存在转义字符。。

**Comment by Lessica** [comment]
试试关闭 magic_quotes 功能

**Comment by 0xJacky** [comment]
感谢大神，关闭magic_quotes后的确可以统计了。
