### ISSUE TITLE
批量上传截图问题反馈

### ISSUE THREAD

**Issue by zikexiaozi** [82Flex/WEIPDCRM#27]
上传路径发生变化，

编辑  删除  18 28 /manage/image/20150731/20150731143508_76476.png 
  编辑  删除  19 28 /manage/image/20150731/20150731143516_24535.png 
  编辑  删除  20 28 /manage/image/20150731/20150731143524_62482.png 
  编辑  删除  21 28 /manage/image/20150731/20150731143535_89000.png 
  编辑  删除  33 32 //image/20150802/20150802152708_23415.png 
  编辑  删除  32 32 //image/20150802/20150802152708_17062.png 
  编辑  删除  31 32 //image/20150802/20150802152707_91992.png 
  编辑  删除  30 32 //image/20150802/20150802152707_26985.png 
  编辑  删除  29 32 //image/20150802/20150802152707_88114.png 
  编辑  删除  28 32 //image/20150802/20150802152706_12926.png 
 并且多了一个斜杠，无法打开图片

**Comment by Hintay** [comment]
正在排查问题中

**Comment by Hintay** [comment]
已在 Commit 1d69c5e 中修复，请更新并及时反馈。
