### ISSUE TITLE
删除截图 ，FTP查看，截图服务器上并没有删除

### ISSUE THREAD

**Issue by zikexiaozi** [82Flex/WEIPDCRM#28]
如题

**Comment by Hintay** [comment]
考虑到有可能只是勿加其他软件包截图，并有可能会出现多个软件包共用截图的情况，因此在查看软件包页删除截图指的是删除该图片与该软件包的联系，并非直接删除图片文件。
当前并未设计直接删除图片的入口。

**Comment by zikexiaozi** [comment]
可否更新上传截图命令功能，以软件包名称或标识符命名，方便查找

**Comment by Hintay** [comment]
按此情况，若出现多个软件包共用截图该如何处理？

**Comment by zikexiaozi** [comment]
可添加查看服务器图片选择功能

**Comment by Hintay** [comment]
因为图片上传后的后台处理与主程序分离，因此以标志符进行命名可能有些麻烦。另外以月份作文文件夹还是以标识符作为文件夹等各种问题还需仔细研究，有空时会进行此方面的讨论与实现。

**Comment by zikexiaozi** [comment]
还请给出升级 sql 语句，将前期的截图在 /manage/image/的图片改为/image/方便服务器文件管理
然后手动将 /manage/image/ 下的文件全部转移到 /image/下
`Image`SELECT \* FROM `cydia_ScreenShots` WHERE 1

**Comment by Lessica** [comment]
技术支持需要商业授权，在此反馈问题请静待更新！这是因为你自己原因所导致需要额外的 sql 语句的，还请不要得寸进尺。
