### ISSUE TITLE
为什么存在上传限制？

### ISSUE THREAD

**Issue by zikexiaozi** [82Flex/WEIPDCRM#29]
上传软件包限制大小仅为10M，一般软件足矣，但对于系统字体来说。需要50M左右，建议增大上传软件包限制。

**Comment by zikexiaozi** [comment]
建议增大上传软件包限制

**Comment by Hintay** [comment]
使用中已有说明，过大软件包请使用 FTP 等传输软件进行上传。
PHP 并不适合过大文件传输。

**Comment by Lessica** [comment]
上传限制是由 php、网页服务器、甚至 CDN 和运营商所限制的，以后国人这种奇葩问题 Hintay 你就不要回答了吧，感觉浪费精力。
