### ISSUE TITLE
Already Installed, when the database is empty.

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#30]
Hello, i tried to install the repository to http://cydia.roblox-network.com/
It did work yesterday, but it didn't work in cydia, when i typed in cydia.roblox-network.com
and when i removed anything in the MySQL and re installed the whole thing, this message comes up

"Already Installed
You appear to have already installed DCRM. You should clear your old database tables before reinstall."

**Comment by master3395** [comment]
I had to open up setup-install.php and fill in the name and username, then it worked. But the repository isn't getting it's adress, i can't add it in cydia?

**Comment by Lessica** [comment]
You'd better use $(PROJECT_ROOT)/main/ as your website's root path.
