### ISSUE TITLE
软件截图问题反馈

### ISSUE THREAD

**Issue by zikexiaozi** [82Flex/WEIPDCRM#31]
在苹果手机浏览器safafi 找开软件页面可
![img_0866](https://cloud.githubusercontent.com/assets/13590006/9148912/345fbd40-3dc2-11e5-8ebb-0cd5254c0f48.PNG)
![img_0867](https://cloud.githubusercontent.com/assets/13590006/9148913/3a1d59b8-3dc2-11e5-9d12-b4c17a26995f.PNG)

以看到  截图预览功能  ，在cydia里面有的有截图预览，有的没有

**Comment by Lessica** [comment]
You should set the "depiction" property for each package correctly, and this is not a bug. It's a wrong usage.
