### ISSUE TITLE
Sell apps

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#32]
Hello, is it possible to sell your apps, like using paypal or any other paying service?

**Comment by Lessica** [comment]
No, you should submit your apps or tweaks to the Cydia Store. WEIPDCRM cannot handle with commercial packages correctly and safely.

**Comment by Hintay** [comment]
DCRM does not provide a business level commercial function. 
You can use 'UDID Binding' and 'Protection of Packages' if your demand is not high, and you might manually bind UDID and fill in the purchase link.
