### ISSUE TITLE
网站从win2003搬往centos后 icons 全部显示空白

### ISSUE THREAD

**Issue by haoerloveyou** [82Flex/WEIPDCRM#33]
系统Centos6.5 或70
环境全部用yum安装
apache2 yum install httpd
mysql yum install mysql mysql-server
php5 yum install php
php5 获得 mysql支持 yum install php-mysql php-gd php-imap php-ldap php-mbstring php-odbc php-pear php-xml php-xmlrpc
仅以上操作，其他无。
出现问题：所有DCRM自带icons无法显示 包括QQ 微博 支付宝 icons等
测试多台服务器问题依旧 
特来反馈和求助

**Comment by Lessica** [comment]
Please use English instead of Chinese. We will not answer the same question in two languages.
Anyone who uses WEIPDCRM must have a basis of Web Debugging. For example, Chrome provides a series of debugging tools. You should check the HTTP return code now, and check why the icons are not accessible.

We will not reply to this issue anymore until you translate it, thanks.
P.S. If you just come here and ask for solutions, with no devotion, you are not welcome.

**Comment by haoerloveyou** [comment]
不知道说什么......或许是我问问题态度不够好。如果有下次，我带着code来。英语不怎么行，但客随主便，下一次查字典也争取用英文，另外，不知道你说的贡献指的什么，如果是钱的话，同样作为学生的我，除了是比你大几岁外，没用什么收入。做个源属于一个人做饭一群人吃，还自备食材的情况。没有像ljk搞会员，也没用搞捐款。钱上确实帮不上什么忙，如果有其他地方能帮得上的非常乐意为之。最后，还是非常感谢。

**Comment by Lessica** [comment]
Codes, trails, and experiences are more acceptable, not money. It is an open source project, but if you need trouble-shooting, you should purchase a commercial license. Developers cost too much time and energy.
You may use the Chrome's "Inspect Elements" function to find if there is an HTTP 404, 403, 400 or 502 code. That helps.

**Comment by Hintay** [comment]
You can use Firebug Add-on to check http code if your browser is Firefox.
如果你使用的是 Firefox，你可以使用 Firebug 擴展來檢查 HTTP 碼。

**Comment by Lessica** [comment]
贡献方面，代码，尝试，有意义的经历都是可行的。
这是一个开源项目，但是如果你自己搭的源需要特殊的，一对一地解决问题，而又没做贡献。你需要支付商业技术支持。不然为什么开源开发者要耗费了时间和精力去单独解决你个人连续提出的多个问题呢。
建议你使用 Chrome 的检查元素，试着找找为什么图标不能被显示，也许是 404, 403, 400 或者 502 错误，这有助于你自行定位与解决问题，而不是一昧的请求针对你个人的特殊帮助。

**Comment by haoerloveyou** [comment]
apache 后台错误404+（302） 考虑rewrite 出现的问题，链接只能访问根目录下的图片。比如把alipay放入wwwroot 就能访问了，放在icons 和icons/default 均不能访问。另外，我发现你写入数据库表用的驼峰命名，以apt_user为例 win下位apt_user 没问题 能正常识别，导入linux后会服务器会出现apt_User请求错误，需要手动修改数据库表名才能接入，希望算个贡献

**Comment by Lessica** [comment]
It means the rewrite rules on CentOS were different from those on Windows.

You should always pay attention to the migration from Windows to Linux...
Hintay had been once trapped by the CASE SENSITIVE problem...XD
So we recommend Linux-based environment.

**Comment by haoerloveyou** [comment]
Problem has been solved . The question is that apache(2.2.15) in yum for CentOS6.5 is confict with DCRM. The icons alias's default address is same in DRCM's icons.To Solve the problem we need note the Alias and change the rewrite permission .like the under example. thanks

#Alias /icons/ "/var/www/icons/"
<Directory "/var/www/icons">
    Options Indexes MultiViews FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from All
</Directory>

**Comment by Lessica** [comment]
Thanks for reporting. XD
