### ISSUE TITLE
Repository not working in cydia, but shows on website.

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#34]
Hello, the repository show's up on http://roblox-network.com/cydia/main/
and in the settings it's also the same adress http://roblox-network.com/cydia/main/
But it doesn't work in cydia.
I also tried
http://cydia.roblox-network.com/main/
Why doesn't it work?

**Comment by Lessica** [comment]
Check the url rewrite and your vhosts config.
There is nothing wrong with the WEIPDCRM, please do not open any other invalid issue.
