### ISSUE TITLE
Adding icons not working

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#35]
Hello, i'm trying to add icons to the sections, but it doesn't work, it just makes a image
![a88dd08416341acbe8c343843bc3996e](https://cloud.githubusercontent.com/assets/4199669/9290260/e40d3438-438b-11e5-84c2-4ad86e2f0539.png)
If i remove the image, and let's the default image be, it show's the default question mark.

**Comment by Lessica** [comment]
Solved in issue #33 .
