### ISSUE TITLE
encountered a section with no Package:header

### ISSUE THREAD

**Issue by ZhangShanFeng1114** [82Flex/WEIPDCRM#38]
rt

**Comment by Hintay** [comment]
I'm not sure what you asking, please describe your problem in detail.

**Comment by ZhangShanFeng1114** [comment]
之前从1.5升级到了现在的版本，然后每当Cydia刷新完后，就会有黄字，encountered a section with no Package:header

**Comment by Hintay** [comment]
You may want to run apt-get update to correct this problem.

**Comment by ZhangShanFeng1114** [comment]
http://dl.iduuke.com/1.png
你看看截图，上传图片总出错

**Comment by ZhangShanFeng1114** [comment]
好奇怪啊，昨天测试，删除我的源就没提示了，今天发现是3k助手源的问题。
