### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#39]
Hello, maybe WEIPDCRM Should have a way of inserting IPA files, and then converting it into DEB.
Many people are looking for ways to convert IPA to deb, but there's less and less ways to do so.

**Comment by Lessica** [comment]
Servers will be killed by the heavy extracting and compressing loads...

**Comment by master3395** [comment]
What if you have two functions, one that extracts and one that compresses, i really see that there has to be some converter some were.
And i was looking at online converters, i know that myrepospace, had one named ideb, but it was apperently taken down. and i know that my site doesn't kill heave load, but making it into different levels, like you do on the import, would proabebly lift the load.

**Comment by master3395** [comment]
What about letting us install ipa files, instead of converting perhaps

**Comment by Lessica** [comment]
Bad ideas.
IPA files are actually zip files, maybe we can extract the './payload/*.app' to '/Applications/'. PHP can uncompress them and then compress them in LZMA format. So they can be ran as system apps. That may cause many unexpectable problems.
To run them as users apps, we should find a command line tool that can install IPA files. It's always unstable and slow.
I think it is not worth to publish IPAs via Debian APT Server, and itms-service with HTTPS is more compatible and secure.

**Comment by ljk4160** [comment]
You can create *.plist file on your https server,Then use AppStore to install *.ipa App.The bandwidth of the Cydia repo source is fatal to the IPA Conversion deb.
