### ISSUE TITLE
Warning: The server does not support the URL Rewrite, DCRM will not be able to use.

### ISSUE THREAD

**Issue by sup3rgiu** [82Flex/WEIPDCRM#4]
Hi, I'm using Altervista server and I'm not sure if it's allow URL Rewrite.
Do u know how can I fix this problem?

**Comment by Hintay** [comment]
Hello. What contents show when you visit http://{YOUR_REPO_URL}/rewritetest ?

**Comment by elalemanyo** [comment]
I have also the same problem. When I try to visit the URL I get a 500 error.

**Comment by elalemanyo** [comment]
Hi,
I fix the http://{YOUR_REPO_URL}/rewritetest, but to do that I needed to change a function from function.php.

``` php
function base_url(){
  $sitepath = str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace('\\', '/', ABSPATH));
  $siteurl = htmlspecialchars(($_SERVER['SERVER_PORT'] == '443' ? 'https://' : 'http://').$_SERVER['HTTP_HOST']);
  define('BASE_URL', $siteurl);
}
```

Now I have a 500 error when I try to call http://{YOUR_REPO_URL}/manage, any Idea how I can fix that?

I think that the Problem have something to do with this line:

``` php
define('ABSPATH', dirname(MANAGE_ROOT).'/');
```

Thanks!

**Comment by Lessica** [comment]
Now please try the latest version, and give us feedback in another issue.
