### ISSUE TITLE
常规页面问题

### ISSUE THREAD

**Issue by ZhangShanFeng1114** [82Flex/WEIPDCRM#42]
![qq 20151110195427](https://cloud.githubusercontent.com/assets/10368342/11061862/049f9af4-87e5-11e5-8375-edc8fcc7715b.png)
使用的iis，是因为这个原因吗？

**Comment by Hintay** [comment]
本地IIS 7测试正常，请检查文件版本与完整性。

**Comment by ZhangShanFeng1114** [comment]
好的，刚刚测试了下，应该是上次更新FTP上传不完整导致的。谢谢
