### ISSUE TITLE
Help Me To Fix This Error

### ISSUE THREAD

**Issue by iperispc** [82Flex/WEIPDCRM#44]
When i try to install DCRM on my website getting the error , it will say : bzcompress not supported , and after installing i will getting Error 500.
please how to fix it , i'm very very ..
see this photo from down below : 
![bz2](https://cloud.githubusercontent.com/assets/9453211/11229453/364421dc-8d4a-11e5-87e4-199cb42ec539.png)
need

**Comment by shlyahten** [comment]
+

**Comment by ZhangShanFeng1114** [comment]
+

**Comment by MiRO92** [comment]
i had the same error, have u fixed it?

**Comment by Hintay** [comment]
Fixed in commit ebe5e2a.
