### ISSUE TITLE
新版本更新代码(1.7.php)有一处错误

### ISSUE THREAD

**Issue by lemon4ex** [82Flex/WEIPDCRM#46]
非升级安装后，出现错误：
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD `System_Support` longtext NOT NULL AFTER `Video_Preview`' at line 1

解决办法：
将1.7.php中下面的代码：
DB::query("ADD `System_Support` longtext NOT NULL AFTER `Video_Preview`");
改为
DB::query("ALTER TABLE `".DCRM_CON_PREFIX."Packages` ADD `System_Support` longtext NOT NULL AFTER `Video_Preview`");

**Comment by Hintay** [comment]
Thanks, fixed in commit d8d07a75.
