### ISSUE TITLE
Request for premium version

### ISSUE THREAD

**Issue by paulu-alfer** [82Flex/WEIPDCRM#48]
Imagine that all have a repo like bigboss,Then who upload own package in to this repo and how download it. every one make one for themselves open source script always have bug , and its really for hacker to found bug and crack the script.
This is really big problem

i hope you understand my mean

**Comment by Showian** [comment]
I totally agree with you, i also told Hintay in the past about somethings like it . this is to bad that pro version is free .They need to know this.
