### ISSUE TITLE
任意文件上传漏洞

### ISSUE THREAD

**Issue by lemon4ex** [82Flex/WEIPDCRM#49]
/main/manage/plugins/uploadify/uploadify.php

这个文件漏洞太多：
1.没有限制用户访问
2.没有判断上传文件类型，可以上传任意文件到upload文件夹

apt.82flex.com貌似就是被这个黑了，这个uploadify.php插件漏洞百出，网上很多人提到了。

解决办法：
1.参考http://www.uploadify.com/documentation/uploadify/making-uploadify-secure/
2.直接就不使用这个插件

**Comment by Hintay** [comment]
Fixed.
Please contact us directly via Email if found security bugs. Public details are not appropriate before fixed.

**Comment by Showian** [comment]
Fixed?!! hehh
its not possible, Hintay as you know open source software always hack-able  and always security bugs. as the hacker in 82_flex says, there are other holes (bug).

**Comment by Hintay** [comment]
THIS BUG IS FIXED.
If you found other security bugs, please open a new issue or pull request to help us, rather than sarcastic.
