### ISSUE TITLE
Suggest "HTTPS option"

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#53]
Currently when i switch to HTTPS on my website, the content get's moved, and things error out.

**Comment by Hintay** [comment]
It work well in local test, please check your server config.
![20160204145546](https://cloud.githubusercontent.com/assets/1146488/12808097/7155dd54-cb4f-11e5-839b-a75b03a97f16.png)

**Comment by master3395** [comment]
Ok, i'll check my site if they messed something up there.
