### ISSUE TITLE
Issues with (SITE_URL) and with HTTPS

### ISSUE THREAD

**Issue by MiRO92** [82Flex/WEIPDCRM#54]
hiii again
sorry for bothering you again but i'm having 2 issues, I hope u fix

1) when i make my repo as **repo**.mywebsite.com, I will have issue with (SITE_URL) in both **viewing Package** page and **Contact us** page

the issue is the Images and Stylesheets does not load because the (SITE_URL) is wrong 

go to 
http://repo.miro92.com/view/1
or 
http://repo.miro92.com/contact/1

u'll see that it puts 2 **repo** directory 

![screen shot 2016-02-09 at 22 57 54](https://cloud.githubusercontent.com/assets/3205572/12928819/ad27ffb2-cf80-11e5-84c2-ede38afe866c.png)

it should not put another **repo** directory `http://repo.miro92.com/repo/css/menes.min.css`
it should be `http://repo.miro92.com/css/menes.min.css`

but if i register my repo in this form mywebsite.**repo**.com  it will be ok

this bug only if i register my repo in this form **repo**.mywebsite.com

2) when i use SSL in my website, then it will be the same problem as above it will not put **https://** in (SITE_URL)  so the stylesheets will not work and even the Manage page looks different an messy

here is an example:
first go to 
http://repo.miro92.com/

then go to 
https://repo.miro92.com/

this is the manage page
![screen shot 2016-02-09 at 23 37 18](https://cloud.githubusercontent.com/assets/3205572/12929911/900184e8-cf86-11e5-8ebb-cbde66ef29a5.png)
![screen shot 2016-02-09 at 23 37 46](https://cloud.githubusercontent.com/assets/3205572/12929910/8fa6b8e2-cf86-11e5-9ce0-f58533111905.png)

3) when i disable the downgrade feature it will NOT turn off and Cydia still showing downgrading.

PS: i did like 9-12 reinstall and all these issues existing in every install
i hope u'll fix both issues
thank you

**Comment by Hintay** [comment]
1) I test it in localhost, and Second-level domains work fine for me. So maybe you need check your VirtualHost config?
2) I can not browse your repo with SSL, that said 'Server not responding'.
3) Do you have rebuild the list after you disable downgrade feature?

**Comment by MiRO92** [comment]
> 1) I test it in localhost, and Second-level domains work fine for me. So maybe you need check your VirtualHost config?

where can i check this? and what exactly should i look for?

> 2) I can not browse your repo with SSL, that said 'Server not responding'.

oops sorry i turn SSL off by accident, u can try now :)

**Comment by Hintay** [comment]
HTTPS issues fixed in commit 03f674e (I hope so), you can update your DCRM version to latest :).
But I still have no idea about the SITE_URL issues for you. You need check your VirtualHost config that names like 'vhost.conf' in Apache's config directory.

**Comment by MiRO92** [comment]
hii
thank you, i will try update it now
?
and i dont have vhost.conf nor Apache's config directory in my website :(  where should i find it?

**Comment by Hintay** [comment]
Hi, are you using Shared Hosting? You need to contact your web server provider if your website is on Shared Hosting.
By the way, we used "$_SERVER['PHP_SELF']" to generate site's path.

**Comment by andrewwiik** [comment]
In what file is this function as I notice when setting this up it always
adds extra slashes to the end and things and this causes depiction issues
