### ISSUE TITLE
Using HTTPS content loaded over HTTP problem

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#55]
Hello,

When i use HTTPs, i got a problem.
Some of the content is loaded over HTTP
As you can see on the image below, i got a warning from chrome (the grey badge at the top right of the URL bar) saying "are you sure you want to load un safe scripts?
Also there might be a problem converting the Urls to HTTPS in the system, if we don't have to do it our self?

![46b4b9724199933d8c0dab0179e47307](https://cloud.githubusercontent.com/assets/4199669/13198177/6ec7dc62-d802-11e5-82f4-990ceeeaaea4.png)

Below is a image between HTTP and HTTPS

![ee99f964872d0bae6d616e1276d063bb](https://cloud.githubusercontent.com/assets/4199669/13198396/ff840316-d807-11e5-97a4-3fcd4df343dc.png)

![d3e7e22374ad3cdeda1560d82615618a](https://cloud.githubusercontent.com/assets/4199669/13198384/cad816ac-d807-11e5-9931-9a3027ffd33f.png)

**Comment by Hintay** [comment]
Fixed in commit 03f674e.

**Comment by master3395** [comment]
Ok, will close this.

**Comment by Hintay** [comment]
Sorry for missing issues, fixed in commit 902c463.
