### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by master3395** [82Flex/WEIPDCRM#56]
Hello,
My website has cydia as a sub, but recently i found out that if i have "pretty urls" on my root.
So i get a error saying WEIPDCRM is already installed, for some reason.
I've dissabled pretty urls to install the repository, and that works.
but it would be better if i didn't have to do that in the future.

**Comment by Hintay** [comment]
HI, what is "pretty urls"?

**Comment by master3395** [comment]
Pretty urls is like this:
website.com/page1/page2/page3

but without pretty page it could have been like this if you had spaces on the page name
website.com/page%20%1//page%20%2/

In most websites, pretty urls are a thing. and with that i get the error if it's enabled on root. because cydia is in it's own sub folder.

Using this in my root config.php

$config['url_rewriting'] = 'mod_rewrite';

and a lot of config stuff in .htaccess

Below is both config.php and the .htaccess that is located in root.
I have to clear out both to get the wizzard to work.
(it's always a work around to remove them and add it back after i've done the wizzard, it's just a bit annoying.

Btw the files comes from http://www.cmsmadesimple.org/ (this CMS is in my root.)
[config.txt](https://github.com/82Flex/WEIPDCRM/files/147759/config.txt)
[.htaccess.txt](https://github.com/82Flex/WEIPDCRM/files/147760/default.htaccess.txt)
