### ISSUE TITLE
Help with title

### ISSUE THREAD

**Issue by iphonefacil** [82Flex/WEIPDCRM#58]
Hello,

1 I would like to make the title of the page to be the name of the packahe but it allways shows "**View Package**"

I need it because I want to insert Disqus script and a script to share the depection, and both are based in the page title.

2 And I also would like to suggest the option of showing when a package is "New" or an "Update" in the Latest List.

Thanks a lot and great job.

**Comment by Hintay** [comment]
Added in commit 1cc57d2.
