### ISSUE TITLE
Failed to Fetch POSIX: Connection refused

### ISSUE THREAD

**Issue by bleenStudios** [82Flex/WEIPDCRM#6]
![screen](https://cloud.githubusercontent.com/assets/8205659/6885327/99f679e6-d61b-11e4-8ea4-70d520eed275.png)

Do you know what the problem is?

**Comment by Hintay** [comment]
Hello,

Can you visit your repository by use Safari Borrower in your device?

**Comment by bleenStudios** [comment]
yes that works

**Comment by Hintay** [comment]
Could you provide your repository url for me?

**Comment by bleenStudios** [comment]
u should have an email from me where i tell u the url

**Comment by bleenStudios** [comment]
ok.. i fixed the second error message by renaming the file Release to Release.gpg but the first is still there

**Comment by Hintay** [comment]
Hello,
I can add your repository in my Cydia. 
And Release.gpg is different from Release, this is gpg signature for the Release file. So please do not rename the Release.

**Comment by bleenStudios** [comment]
ok but what should i do? i added a file named de_DE.bz and now there is no error anymore but if i try to install a tweak it downloads and then says hash sum mismatch or so also if i manage a tweak there is Filename: ../downloads/20150329/wmX0FSG9ohzNfNwpjvnXJxvH6M4kKnbm2pOH3TBr.deb and if i rebuild the list or look in Packages there is Filename: ./debs/1.deb

**Comment by bleenStudios** [comment]
Fixed! 

The repo works!

Very nice work!

**Comment by Hintay** [comment]
Hi,
I'm glad your issue has been solved.
By the way, de_DE.bz(`$LANG.bz`) is translation supports of Repository, WEIPDCRM is not support this function now. And without this file has no impact on the normal function.

You can learn more about _Debian Repository Translation Format_ in [Here](https://wiki.debian.org/RepositoryFormat#A.22Translation.22_indices).

**Comment by bleenStudios** [comment]
Yeah thx... 

I'm now having issues with the repo it doesn't show any packages in cydia but there are packages in my repo and i can see them in my cydia mobile website :(

**Comment by bleenStudios** [comment]
Ok i solved the problem ;)

The design and also the whole system of this project is very nice and i would love to help if there is sth where help is needed.
