### ISSUE TITLE
兼容性支持提示不支持填写两位数

### ISSUE THREAD

**Issue by Cydiaptso** [82Flex/WEIPDCRM#61]
例如：在兼容性支持里我填写着：iOS 7.0~IOS 10.9
那么任何一个版本设备都会直接提示为不兼容，除非不填写iOS 10
只要不填写两位数10或者11、12等等之类,例如填写iOS 9就一切正常。
作者您可以试试。

**Comment by Hintay** [comment]
Fixed in commit 0640d7b.
