### ISSUE TITLE
关于后台设置 Rewrite 模式（普通或优雅）报错

### ISSUE THREAD

**Issue by Cydiaptso** [82Flex/WEIPDCRM#62]
[以现在的最新版DCRM为例，在后台设置里更改:Rewrite 模式 选择：普通或优雅模式会红字报错，提示无法配置Rewrite，可能需要更新Rewrite的配置等提示时
如果在manage/settings.php这个文件的753行的$check_url = url_scheme().SITE_URL.'misc';代码下面再建一行并填写这行内容：$check_url = SITE_URL.'misc'; 
之后就可以正常保存并使用DCRM后台设置里的Rewrite 模式了。

注：Rewrite 模式不能正常使用的情况目前测试在个别的虚拟主机上会发生(不是所有虚拟主机都不能使用)
在vps 如腾讯云等就一切正常使用

在回复里不会上传截图，所以上传不了探针截图
不知道这是不是BUG还是我们自身的服务器问题，作者您有时间可以看看

**Comment by Hintay** [comment]
This is an issue for HTTPS detection on some virtual host.
You should upload your host config to help us.

**Comment by Cydiaptso** [comment]
您需要的是探针吗？

**Comment by Cydiaptso** [comment]
截图不会发，我给你发个复制下来的文本版探针：

服务器标识
Linux localhost 2.6.32-279.el6.i686 #1 SMP Fri Jun 22 10:59:55 UTC 2012 i686
服务器操作系统
Linux  内核版本：2.6.32-279.el6.i686
服务器解译引擎
Apache
服务器语言
zh-cn
服务器端口
80
服务器主机名
localhost
绝对路径
/www/users/HA138590/WEB
管理员邮箱
webmaster@HA138590
探针路径
/www/users/HA138590/WEB/tz.php
PHP已编译模块检测
Core  date  ereg  libxml  openssl  pcre  sqlite3  zlib  bcmath  bz2  ctype  curl  dom  
fileinfo  filter  ftp  gd  gettext  hash  iconv  json  mbstring  mcrypt  mysql  SPL  mysqli  
PDO  pdo_sqlite  session  posix  Reflection  standard  shmop  SimpleXML  soap  sockets  SQLite  Phar  sysvsem  
tokenizer  xml  xmlreader  xmlwriter  zip  cgi-fcgi  pdo_mysql  mhash  Zend Guard Loader  
PHP相关参数
PHP信息（phpinfo）：
PHPINFO
PHP版本（php_version）：
5.3.27
PHP运行方式：
CGI-FCGI
脚本占用最大内存（memory_limit）：
128M
PHP安全模式（safe_mode）：
×
POST方法提交最大限制（post_max_size）：
100M
上传文件最大限制（upload_max_filesize）：
100M
浮点型数据显示的有效位数（precision）：
14
脚本超时时间（max_execution_time）：
30秒
socket超时时间（default_socket_timeout）：
60秒
PHP页面根目录（doc_root）：
×
用户根目录（user_dir）：
×
dl()函数（enable_dl）：
×
指定包含文件目录（include_path）：
×
显示错误信息（display_errors）：
√
自定义全局变量（register_globals）：
×
数据反斜杠转义（magic_quotes_gpc）：
×
"<?...?>"短标签（short_open_tag）：
√
"<% %>"ASP风格标记（asp_tags）：
×
忽略重复错误信息（ignore_repeated_errors）：
×
忽略重复的错误源（ignore_repeated_source）：
×
报告内存泄漏（report_memleaks）：
√
自动字符串转义（magic_quotes_gpc）：
×
外部字符串自动转义（magic_quotes_runtime）：
×
打开远程文件（allow_url_fopen）：
√
声明argv和argc变量（register_argc_argv）：
×
Cookie 支持：
√
拼写检查（ASpell Library）：
×
高精度数学运算（BCMath）：
√
PREL相容语法（PCRE）：
√
PDF文档支持：
×
SNMP网络管理协议：
×
VMailMgr邮件处理：
×
Curl支持：
√
SMTP支持：
√
SMTP地址：
localhost
默认支持函数（enable_functions）：
请点这里查看详细！
被禁用的函数（disable_functions）：
system  exec  shell_exec  set_time_limit  passthru  
proc_open  proc_close  proc_get_status  checkdnsrr  getmxrr  
getservbyname  getservbyport  syslog  popen  show_source  
highlight_file  dl  socket_listen  socket_create  socket_bind  
socket_accept  socket_connect  stream_socket_server  stream_socket_accept  sys_getloadavg  
disk_total_space  disk_free_space  posix_ctermid  posix_get_last_error  posix_getcwd  
posix_getegid  posix_geteuid  posix_getgid  posix_getgrgid  posix_getgrnam  
posix_getgroups  posix_getlogin  posix_getpgid  posix_getpgrp  posix_getpid  
posix_getppid  posix_getpwnam  posix_getpwuid  posix_getrlimit  posix_getsid  
posix_getuid  posix_isatty  posix_kill  posix_mkfifo  posix_setegid  
posix_seteuid  posix_setgid  posix_setpgid  posix_setsid  posix_setuid  
posix_strerror  posix_times  posix_ttyname  posix_uname  set_time_limit   
组件支持
FTP支持：
√
XML解析支持：
√
Session支持：
√
Socket支持：
×
Calendar支持
×
允许URL打开文件：
√
GD库支持：
bundled (2.1.0 compatible)
压缩文件支持(Zlib)：
√
IMAP电子邮件系统函数库：
×
历法运算函数库：
×
正则表达式函数库：
√
WDDX支持：
×
Iconv编码转换：
√
mbstring：
√
高精度数学运算：
√
LDAP目录协议：
×
MCrypt加密处理：
√
哈稀计算：
√
第三方组件
Zend版本
2.3.0
ZendGuardLoader[启用] 
√
eAccelerator
×
ioncube
×
XCache
×
APC
×
数据库支持
MySQL 数据库：
√
ODBC 数据库：
×
Oracle 数据库：
×
SQL Server 数据库：
×
dBASE 数据库：
×
mSQL 数据库：
×
SQLite 数据库：
√　SQLite3　Ver 3.7.7.1
Hyperwave 数据库：
×
Postgre SQL 数据库：
×
Informix 数据库：
×
DBA 数据库：
×
DBM 数据库：
×
FilePro 数据库：
×
SyBase 数据库：
×
服务器性能检测
参照对象
整数运算能力检测
(1+1运算300万次)
浮点运算能力检测
(圆周率开平方300万次)
数据I/O能力检测
(读取10K文件1万次)
CPU信息
美国 LinodeVPS
0.357秒
0.802秒
0.023秒
4 x Xeon L5520 @ 2.27GHz
美国 PhotonVPS.com
0.431秒
1.024秒
0.034秒
8 x Xeon E5520 @ 2.27GHz
德国 SpaceRich.com
0.421秒
1.003秒
0.038秒
4 x Core i7 920 @ 2.67GHz
美国 RiZie.com
0.521秒
1.559秒
0.054秒
2 x Pentium4 3.00GHz
埃及 CitynetHost.com
0.343秒
0.761秒
0.023秒
2 x Core2Duo E4600 @ 2.40GHz
美国 IXwebhosting.com
0.535秒
1.607秒
0.058秒
4 x Xeon E5530 @ 2.40GHz
本台服务器
未测试
未测试
未测试

网络速度测试

向客户端传送1000k字节数据
带宽比例按理想值计算
带宽
1M
2M
3M
4M
5M
6M
7M
8M
9M
10M

 未探测 
MySQL数据库连接检测

地址：localhost 端口：3306 用户名： 密码：

函数检测

请输入您要检测的函数：

邮件发送检测

请输入您要检测的邮件地址：

雅黑PHP探针[简体版]v0.4.7
Processed in 1.0019 seconds. 0.65MB memory usage.
返回顶部
