### ISSUE TITLE
关于"等级优先于UDID绑定"

### ISSUE THREAD

**Issue by Cydiaptso** [82Flex/WEIPDCRM#63]
UDID一旦绑定了软件包那么无论此组UDID所在的用户管理等级有多高都无法下载其他的一些已启用保护的低级管理等级的软件包。
我举例详细说明一下：
下面3项是假设数：
1.软件包A(已启用保护，等级中填写1)
2.软件包B(已启用保护，等级中填写1)
3.已添加的UDID在这用C代表(C的用户等级设置为2)

根据上述的数值得出两种结果：
1.如果C不绑定任何软件包，那么C在Cydia里可以正常下载A和B
2.如果C绑定其中的任何一个(假设只绑定了A)，那么那么C在Cydia里只能正常下载A，而B是无法下载的。就算C的等级比B高也是没办法下载的

基于对"等级优先于UDID绑定"这句提示的理解，那么上述问题不知道是不是BUG，还是可能我对于"等级优先于UDID绑定"这句话的意思理解错了？

**Comment by Hintay** [comment]
Hi,
Sorry to tell you that we are no longer maintaining the UDID related functions.
