### ISSUE TITLE
管理UDID大于或等于100页将无法正常跳页

### ISSUE THREAD

**Issue by Cydiaptso** [82Flex/WEIPDCRM#67]
当udid存在的数量大于或等于100页时将无法直接在dcrm的后台里进行指定页数翻页查看。
你的每一次查看都会默认跳转到第一页的udid内容
详细说明：
1.例如udid绑定的个数在dcrm的后台里共有110页
2.如果你想查看跳转到指定某页里的话，在1至99页可以正常跳转。
3.但如果想查看第100页或100之后的页数里的udid就不行
4.无论你选择跳转到100页，还是101页..... 等等大于100或以上的页数都会被自动跳转到第一页。
5.那么如果是这样的话，你想查看或者修改100页之后的一些udid就无法查看或者修改了。
6.因为你无论选择跳转到第几页（100以上）都会默认跳转显示为第一页的内容。
这不知道这是不是bug，或者还是服务器数据库的问题

**Comment by Hintay** [comment]
Sorry to tell you that we are no longer maintaining the UDID related functions.

**Comment by Cydiaptso** [comment]
无论怎样都想对你说声感谢。
