### ISSUE TITLE
(fonts.useso.com)360公共字体库CND挂了！

### ISSUE THREAD

**Issue by Cydiaptso** [82Flex/WEIPDCRM#69]
360提供的公共字体库CND(fonts.useso.com)挂了。
造成后台登陆界面需要极长的时间才能打开。(仅仅是登陆界面有影响,打开登陆页面大约需要80秒)
检查一下。

**Comment by Cydiaptso** [comment]
已看了360的相关公告！已自行动手修复了。

**Comment by Hintay** [comment]
Fixed.
