### ISSUE TITLE
安裝完成後manage/login.php頁面空白

### ISSUE THREAD

**Issue by Hadison** [82Flex/WEIPDCRM#7]
想請問為何會變成這樣呢？
似乎好像都沒在工作

**Comment by Hintay** [comment]
您好，您訪問首頁時顯示什麼？

**Comment by Hadison** [comment]
訪問首頁一整個空白

**Comment by Hintay** [comment]
請嘗試訪問index.php?debug=true

**Comment by Hadison** [comment]
我重新再上傳一次

**Comment by Hadison** [comment]
出現以下錯誤，請問該如何解決？
DCRM System Error

Version file is not writable!
PHP Debug

No. File    Line    Code
1   manage/index.php    23  require_once()
2   system/common.inc.php   68  ErrorHandler()

**Comment by Hintay** [comment]
您好，WEIPDCRM沒有system/version.php的讀寫權限，請嘗試給予system目錄讀寫權限或自行創建空的version.php文件並賦予讀寫權限。

**Comment by Hadison** [comment]
首頁可以看見，但後台入口還是空白
首頁圖檔連結竟然也會顯示不出來，不知道這是不是有權限問題？
http://i.imgur.com/AtnUq54.png

**Comment by Hintay** [comment]
是否是您後台的源地址設置有誤？

**Comment by Hintay** [comment]
訪問後台時使用login.php?debug=true有無輸出調試信息？

**Comment by Hadison** [comment]
網址地址設定是正確
login.php?debug=true 也是空白一片

**Comment by Hintay** [comment]
您可否查看下返回的http code

**Comment by Hadison** [comment]
請問怎麼查看呢？

**Comment by Hintay** [comment]
用Firefox的firebug或者Chrome的控制臺都是可以看的。

**Comment by Hadison** [comment]
http://i.imgur.com/uWBcY8B.png

**Comment by Hintay** [comment]
後台500了，請您看一下system/version.php內的內容並告訴我。

**Comment by Hadison** [comment]
似乎沒有version.php 只有version.inc.php
內容如下
<?php
$_version='1.6.15.4.2';
?>

**Comment by Hintay** [comment]
抱歉，我剛剛說的有誤，就是version.inc.php。
您現記錄的版本已是最新，說明自動更新功能是正常的。最有可能引起500的原因就是此功能，所以理論上應該不會再出現500代碼，您出現此代碼的原因未知。
我在本地開發及伺服器上測試功能均正常，您可以嘗試重新安裝。
若實在無法解決此問題，您可以向我開放部分權限，我直接在您的伺服器上測試。

**Comment by Hadison** [comment]
可方便留下email？我將權限提供給你測試

**Comment by Hintay** [comment]
您點擊我的頭像進入我的主頁即有Email Address

**Comment by Hadison** [comment]
已經發email給你，再請麻煩一下

**Comment by Hintay** [comment]
已更新全新安裝無需再經過自動升級步驟，請嘗試全新安裝最新版。
如問題已解决或未解决，請再次在此迴響，謝謝！

**Comment by uthman3a** [comment]
all i see is white page ! 

https://www.dropbox.com/s/fk62iapnd1ohsg1/Screenshot%202015-07-04%2022.35.28.png?dl=1

**Comment by Hintay** [comment]
Not compatible with PHP 5.6+ now, please check your PHP version.

**Comment by uthman3a** [comment]
so what to do ?

**Comment by Lessica** [comment]
Nothing. DCRM 1.x is not compatible with PHP 5.6+ now, and won't in the future (maybe).

**Comment by MuhamadMustafa** [comment]
i use php 5.4 but all page is blank

**Comment by master3395** [comment]
It doesn't work today, it's just white, and my php is 5.5 not 5.6 it was working yesterday.
