### ISSUE TITLE
关于报告问题与紧急通知

### ISSUE THREAD

**Issue by Cydiaptso** [82Flex/WEIPDCRM#71]
作者您好：
1.DCRM里的报告问题中的“请求升级”提交后会在哪里看到或收到用户反馈的请求？
2.在DCRM设置里面的‘紧急通知’有bug，当你填写上内容后每保存一次就会自动空出一行。。即；如果点击设置里的‘保存’10次就会在将紧急通知里面的文字内容空出10行的间隔。

**Comment by xkb888** [comment]
确实有这个问题
