### ISSUE TITLE
关于Cydia添加源不显示名称问题

### ISSUE THREAD

**Issue by xkb888** [82Flex/WEIPDCRM#72]
作者您好
首先感谢您带来这么好的作品
请求您的帮助，在配置完DCRM后，已经设置了源名称信息，但手机在Cydia添加源 却不显示源名称。
直接通过网页访问可以看见名称。
网页主机信息：服务器配置：双路至强 Intel Xeon E5-2690 2.9Ghz 32G内存 1TB SSD硬盘 100M共享带宽 Windows Server 2012 R2  Mysql  PHP5.3  
配置DCRM过程中自检服务器正常

**Comment by xkb888** [comment]
![qq 20161011093006](https://cloud.githubusercontent.com/assets/22758138/19256044/f629d96c-8f95-11e6-9c3e-b5be958699a1.png)
![qq 20161011093041](https://cloud.githubusercontent.com/assets/22758138/19256050/fe753a26-8f95-11e6-93bb-a881be0bb0e7.png)
![qq 20161011093125](https://cloud.githubusercontent.com/assets/22758138/19256060/0e3bd0fa-8f96-11e6-8647-ee265c01e286.png)
![qq 20161011093206](https://cloud.githubusercontent.com/assets/22758138/19256067/20a7efe4-8f96-11e6-9641-c10f6862ff96.png)

**Comment by Cydiaptso** [comment]
需要刷新列表后才能生效！！！
同时请注意你的符号！
建议纯中文或中英组合！但不要用符号！

**Comment by xkb888** [comment]
@lzl0306 谢谢你的建议，测试了一下，问题依然存在。
![f](https://cloud.githubusercontent.com/assets/22758138/19293698/1f543efe-9059-11e6-846b-9a81c373c563.jpg)
![d](https://cloud.githubusercontent.com/assets/22758138/19293709/36a39cb2-9059-11e6-9179-307caf0e9d76.jpg)
![20925590989184708](https://cloud.githubusercontent.com/assets/22758138/19293713/4103ab52-9059-11e6-96ea-6dd5061afce3.jpg)
![_20161012085012](https://cloud.githubusercontent.com/assets/22758138/19293716/499b1804-9059-11e6-83ef-68b2b8e2514b.jpg)

**Comment by Cydiaptso** [comment]
你的DCRM没有给权限！权限请设置0755与root  wheel

**Comment by xkb888** [comment]
@lzl0306 我给的是0777
![_20161012085944](https://cloud.githubusercontent.com/assets/22758138/19293865/8ad99d4e-905a-11e6-9fe7-c8827ab82e64.jpg)

**Comment by Cydiaptso** [comment]
此问题曾经我在虚拟主机上出现过，你用的上虚拟主机还是vps？
如果是vps建议试试用wdcp建站
如果你虚拟主机建议报个工单联系一下主机客服

**Comment by xkb888** [comment]
@lzl0306 虚拟主机
我不知道具体是哪里出了问题，所以无法跟客服沟通，请您指点。

**Comment by Cydiaptso** [comment]
请检查system/config/autofill.inc.php这个文件是否变化了。
它的记录软件源相关信息的。
你可以尝试打开它来查看一下。

**Comment by xkb888** [comment]
@lzl0306 里面有这前修改的信息，但是重新设置源名称后，再刷新列表，文件内容没有变化。

**Comment by xkb888** [comment]
@lzl0306 里面有以前修改的名称信息，但是重新设置源名称后，再刷新列表，文件内容没有变化。
如果有之前设置的名称，Cydia里面也应该显示才对吧。

**Comment by xkb888** [comment]
@Lessica 可以帮助我一下吗?

**Comment by xkb888** [comment]
@lzl0306 我这个具体什么问题呢，能帮助我一下吗？

**Comment by 0xJacky** [comment]
请检查 Release 文件的内容

**Comment by xkb888** [comment]
@0xJacky 请看下图，文件内容有变。是服务器的原因吗？
![20161014010322](https://cloud.githubusercontent.com/assets/22758138/19358910/707661c0-91aa-11e6-94e1-042f11f990d8.jpg)

**Comment by xkb888** [comment]
@0xJacky 请看下图，文件内容有变。是服务器的原因吗？
![20161014010322](https://cloud.githubusercontent.com/assets/22758138/19359041/ed6df8c8-91aa-11e6-808a-77bea84bdc3d.jpg)

**Comment by xkb888** [comment]
@0xJacky 请看下图，文件内容有变。是服务器的原因吗？
![_20161014010917](https://cloud.githubusercontent.com/assets/22758138/19359057/02765878-91ab-11e6-9a41-bfee48354c2c.jpg)

**Comment by 0xJacky** [comment]
请确认你可以下载Release 文件
另外，权限不要擅自更改。

**Comment by xkb888** [comment]
可以下载，下载过程正常，没有报错。

发自我的 iPhone

**Comment by xkb888** [comment]
@0xJacky 可以下载，下载过程正常，没有报错。

**Comment by 0xJacky** [comment]
刚才访问过了，你的 Release 文件是不存在的。这个问题与本程序无关，请检查 IIS 的配置。
另外补一刀，windows 下的权限是没有 root:wheel 这种说法的。
