### ISSUE TITLE
在 DCRM 中的保护无法禁用

### ISSUE THREAD

**Issue by Adoream** [82Flex/WEIPDCRM#8]

**Comment by Hintay** [comment]
是软件包的保护功能吗？

**Comment by Adoream** [comment]
对

**Comment by Hintay** [comment]
经测试可以正常禁用。
注意，该选项更改后需要写入软件包。

**Comment by Adoream** [comment]
我在bigboss源下载的插件就无法禁用保护

**Comment by Hintay** [comment]
请提供deb包

**Comment by Jackyxyz** [comment]
请编辑control文件
保留Package、Depends、Name、Version、Architecture、Description、Maintainer、Author、Section字段，其他删除，重新打包即可
亲测可用

**Comment by Hintay** [comment]
已在 Commit 5a5d1b4 中修复。
开 Issues 时请尽量提供详细的信息以供调试，在有足够信息的情况下此 Issuses 其实可以更早解决。
