### ISSUE TITLE
DCRM 中生成的分类图标包安装后无图标

### ISSUE THREAD

**Issue by Adoream** [82Flex/WEIPDCRM#9]

**Comment by pb8DvwQkfRR** [comment]
在软件包里面不存在啊, 只是从源图标读取到这个图标.

**Comment by Adoream** [comment]
我把软件包解包后，在里面存有软图标

**Comment by ljk4160** [comment]
默认生成的图标不能有中文路径，也不能使用中文名，如果要使用中文请自行打包

**Comment by Adoream** [comment]
请问你可以帮我打包一下吗？谢谢！如果我打包后安装会有错误（如下图）
自动生成的图标安装包：http://7xigd0.com1.z0.glb.clouddn.com/icon.deb

**Comment by Hintay** [comment]
您确定这是自动生成的图标包？内部没有包含任何图标数据。

**Comment by Adoream** [comment]
不好意思，我上传错了，新的下载地址：http://7xigd0.com1.z0.glb.clouddn.com/icon.deb

**Comment by Hintay** [comment]
您好，与之前的deb没有任何区别，请仔细检查后再贴出。

**Comment by Adoream** [comment]
这个就是dcrm生成的图标安装包

**Comment by Hintay** [comment]
这是威锋源内的iappstore，可能是cdn导致的缓存，请上传至其他地方。

**Comment by JclMiku** [comment]
？

Date: Fri, 15 May 2015 06:23:57 -0700

**Comment by Hintay** [comment]
不是正确的deb包，请上传至百度云或其它网盘。

**Comment by Adoream** [comment]
http://pan.baidu.com/s/1gdpgFeF

**Comment by Hintay** [comment]
该数据是正确、无误、可正常安装的，您的源分类名称是什么？另外请提供您的Cydia版本。

**Comment by Adoream** [comment]
源分类名称：[JclMiku-xxxx]
Cydia版本：1.1.16

**Comment by Hintay** [comment]
源分类的中括号是您自己添加的吗？在生成图标包的代码中会自动去除源分类的中括号作为文件名。

**Comment by Adoream** [comment]
括号是我自己添加的

**Comment by Hintay** [comment]
您只要去掉源的括号即可正确显示源图标。我将会在下一个版本中添加对中括号的兼容。

**Comment by Adoream** [comment]
嗯，好的。我建议在dcrm中添加一个在线更新系统，我添加了一个在线更新的程序，在设置里面，你可以参考一下下载地址：http://pan.baidu.com/s/1pJBlcd9

**Comment by Hintay** [comment]
自动更新的实现需要服务器的开销，这对于开源免费的项目来说我们没有这样的成本。

**Comment by Adoream** [comment]
我可以免费提供服务器

**Comment by Hintay** [comment]
另外之前考虑添加的自动更新是增量更新，不是您给出的整体更新，开销更大。

**Comment by Adoream** [comment]
增量更新感觉内存消耗会有一点大，所以我就直接制作了一个整体更新的，反正以后如果在服务器这一方面有什么需要的，可以来找我！

**Comment by Lessica** [comment]
图标包生成问题已经得到解决，目前增量更新还是会建议您使用 git pull 命令来完成。
